package src.kalelzar.placeholderengine.common.exception

/**
  * Generic exception generated by PlaceholderEngine components
  *
  * @unit
  * @param msg the message of the exception
  */
case class PlaceholderEngineError(msg: String) extends Exception(msg)
